### ISSUE TITLE
Slash Commands not registering - DJS v13

### ISSUE THREAD

**Issue by net-tech** [AlexzanderFlores/WOKCommands-v2#2]
Wok does not seem to be registering slash commands.

Index excerpt https://gist.github.com/net-tech/4eb969f815ce0ea3bcd77c109cfee502

Command excerpt https://gist.github.com/net-tech/1aac0c3321e1ffd1ad31c22de6805a4f

No errors are raised during startup.

**Comment by net-tech** [comment]
This seems to be a result of #1.

**Comment by AlexzanderFlores** [comment]
This should be fixed as of version 2.0.3
